//
//  RegisterPresenter.swift
//  Hu&Te
//
//  Created BigSur on 20/05/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation
import PKHUD

// MARK: View -
protocol RegisterViewProtocol: class {
    func registerSuccess()
    func registerFailed(error: String)
}

// MARK: Presenter -
protocol RegisterPresenterProtocol: class {
	var view: RegisterViewProtocol? { get set }
    var user: UserEntity? {get set}
    func register(name: String, email: String, phone: String, password: String)
}

class RegisterPresenter: RegisterPresenterProtocol {
    var user: UserEntity?
    

    weak var view: RegisterViewProtocol?

    func register(name: String, email: String, phone: String, password: String){
        HUD.show(.progress)
        Provider.shared.loginAPIService.register(name: name, email: email, phone: phone, password: password, success: { [weak self] (user) in
            guard let user = user, let strSelf = self else { return }
            HUD.hide()
            if user.error == nil {
                strSelf.user = user
                strSelf.view?.registerSuccess()
            } else {
                strSelf.view?.registerFailed(error: user.error ?? "Something went wrong. Try again")
            }
            
        }) { (error) in
            HUD.hide()
            self.view?.registerFailed(error: error?.localizedDescription ?? "Something went wrong")
        }
    }
}
