//
//  RegisterViewController.swift
//  Hu&Te
//
//  Created BigSur on 20/05/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class RegisterViewController: UIViewController, RegisterViewProtocol {

    @IBOutlet weak var tfName: InputView!
    @IBOutlet weak var tfEmail: InputView!
    @IBOutlet weak var tfPhone: InputView!
    @IBOutlet weak var tfPassword: InputView!
    @IBOutlet weak var tfConfirmPassword: InputView!
    var presenter: RegisterPresenterProtocol

	init(presenter: RegisterPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "RegisterViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()

        presenter.view = self
        setupUI()
    }
    
    func setupUI(){
        tfName.setupData(title: "Name")
        tfEmail.setupData(title: "Email")
        tfPhone.setupData(title: "Phone")
        tfPassword.setupData(title: "Password")
        tfConfirmPassword.setupData(title: "Confirm Password")
    }
    
    @IBAction func onTapLogin(_ sender: Any) {
        if (tfName.textField.text == "" || tfPhone.textField.text == "" ) {
            showAlert("Error", message: "Please fill all information!")
            return
        }
        if (tfPassword.textField.text != tfConfirmPassword.textField.text) {
            showAlert("Error", message: "Confirm password isn't correct!")
            return
        }
        
    }
    
    @IBAction func onTapBackLogin(_ sender: Any) {
        navigationController?.pushViewController(LoginViewController(presenter: LoginPresenter()), animated: true)
    }
}
