//
//  RegisterViewController.swift
//  Hu&Te
//
//  Created BigSur on 20/05/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class RegisterViewController: UIViewController, RegisterViewProtocol {

	var presenter: RegisterPresenterProtocol

	init(presenter: RegisterPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "RegisterViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()

        presenter.view = self
        presenter.viewDidLoad()
    }

}
