//
//  SpeakerViewController.swift
//  Hu&Te
//
//  Created BigSur on 08/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit
import SwiftyGif

class SpeakerViewController: UIViewController {

    @IBOutlet weak var vGif: UIImageView!
    var presenter: SpeakerPresenterProtocol
    @IBOutlet weak var lbValue: UILabel!
    
	init(presenter: SpeakerPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "SpeakerViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()
        presenter.view = self
        presenter.getSpeaker()
        do {
            let gif = try UIImage(gifName: "speaker.gif")
            vGif.setGifImage(gif, loopCount: -1)
        } catch {
            print("Fail")
        }
    }

    @IBAction func onTapDismiss(_ sender: Any) {
        self.dismiss(animated: true, completion: nil)
    }
    @IBAction func onTapDescrease(_ sender: Any) {
        if (presenter.speakerValue - 100 >= 0) {
            presenter.speakerValue = presenter.speakerValue - 100
            lbValue.text = "Value: \(presenter.speakerValue)"
            presenter.setSpeaker()
        } else {
            presenter.speakerValue = 0
            lbValue.text = "Value: \(presenter.speakerValue)"
            presenter.setSpeaker()
        }
    }
    
    @IBAction func onTapIncrease(_ sender: Any) {
        if (presenter.speakerValue + 100 <= 1023) {
            presenter.speakerValue = presenter.speakerValue + 100
            lbValue.text = "Value: \(presenter.speakerValue)"
            presenter.setSpeaker()
        } else {
            presenter.speakerValue = 1023
            lbValue.text = "Value: \(presenter.speakerValue)"
            presenter.setSpeaker()
        }
    }
}


extension SpeakerViewController: SpeakerViewProtocol {
    func getValueSuccess() {
        lbValue.text = "Value: \(presenter.speakerValue)"
    }
    
    func getValueFailed(error: String) {
        showAlert("Error", message: error)
    }
}
