//
//  SpeakerViewController.swift
//  Hu&Te
//
//  Created BigSur on 08/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit
import SwiftyGif

class SpeakerViewController: UIViewController, SpeakerViewProtocol {

    @IBOutlet weak var vGif: UIImageView!
    var presenter: SpeakerPresenterProtocol

	init(presenter: SpeakerPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "SpeakerViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()
        presenter.view = self
        do {
            let gif = try UIImage(gifName: "speaker.gif")
            vGif.setGifImage(gif, loopCount: -1)
        } catch {
            print("Fail")
        }
    }

    @IBAction func onTapDismiss(_ sender: Any) {
        self.dismiss(animated: true, completion: nil)
    }
}
