//
//  ManagePresenter.swift
//  Hu&Te
//
//  Created BigSur on 05/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation
import PKHUD

// MARK: View -
protocol ManageViewProtocol: class {
    func getUsersSuccess()
    func getUsersFailed(error: String)
    
    func deleteUserSuccess()
    func deleteUserFailed(error: String)
}

// MARK: Presenter -
protocol ManagePresenterProtocol: class {
	var view: ManageViewProtocol? { get set }
    var users: [UserEntity] {get set}
    func getUsers()
    func deleteUser(id: String)
}

class ManagePresenter: ManagePresenterProtocol {
    var users: [UserEntity] = []
    weak var view: ManageViewProtocol?

    func getUsers(){
        HUD.show(.progress)
        Provider.shared.profileAPIService.getUsers(success: { [weak self] (data) in
            guard let data = data, let strSelf = self else { return }
            HUD.hide()
            if data.error == nil {
                strSelf.users = data.users ?? []
                strSelf.view?.getUsersSuccess()
            } else {
                strSelf.view?.getUsersFailed(error: data.error ?? "Something went wrong. Try again")
            }
            
        }) { (error) in
            HUD.hide()
            self.view?.getUsersFailed(error: error?.localizedDescription ?? "Something went wrong")
        }
    }
    
    func deleteUser(id: String){
        HUD.show(.progress)
        Provider.shared.profileAPIService.deleteUser(id: id, success: { [weak self] (user) in
            guard let user = user, let strSelf = self else { return }
            HUD.hide()
            if user.error == nil {
                strSelf.view?.deleteUserSuccess()
            } else {
                strSelf.view?.deleteUserFailed(error: user.error ?? "Something went wrong. Try again")
            }
            
        }) { (error) in
            HUD.hide()
            self.view?.deleteUserFailed(error: error?.localizedDescription ?? "Something went wrong")
        }
    }
}
