//
//  HomeViewController.swift
//  Hu&Te
//
//  Created BigSur on 20/05/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class HomeViewController: UIViewController, HomeViewProtocol {

    @IBOutlet weak var lbSpeaker: UILabel!
    @IBOutlet weak var lbUser: UILabel!
    @IBOutlet weak var lbTemp: UILabel!
    @IBOutlet weak var lbHumid: UILabel!
    var presenter: HomePresenterProtocol

	init(presenter: HomePresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "HomeViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()
        presenter.view = self
        setupUI()
    }
    
    func setupUI(){
        lbSpeaker.transform = CGAffineTransform(rotationAngle: CGFloat.pi / 2)
    }
    
    @IBAction func onTapPofile(_ sender: Any) {
        navigationController?.pushViewController(ProfileViewController(presenter: ProfilePresenter()), animated: true)
    }
    
    @IBAction func onTapGraph(_ sender: Any) {
        
    }
    
    @IBAction func onTapSpeaker(_ sender: Any) {
        
    }
    
    @IBAction func onTapSettings(_ sender: Any) {
        navigationController?.pushViewController(SettingViewController(presenter: SettingPresenter()), animated: true)
    }
    
    @IBAction func onTapHistory(_ sender: Any) {
        
    }
}
