//
//  HomeViewController.swift
//  Hu&Te
//
//  Created BigSur on 20/05/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit
import PKHUD

class HomeViewController: UIViewController {

    @IBOutlet weak var lbSpeaker: UILabel!
    @IBOutlet weak var lbUser: UILabel!
    @IBOutlet weak var lbTemp: UILabel!
    @IBOutlet weak var lbHumid: UILabel!
    var presenter: HomePresenterProtocol
    var timer = Timer()
    var isCallTimer = false
	init(presenter: HomePresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "HomeViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)
        isCallTimer = true
        lbUser.text = "Hi, " + (UserDefaultHelper.shared.userName ?? "Username")
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(true)
        isCallTimer = false
    }

	override func viewDidLoad() {
        super.viewDidLoad()
        presenter.view = self
        HUD.show(.progress)
        presenter.getTemperature()
        presenter.getHumidity()
        navigationController?.navigationBar.isHidden = true
        setupUI()
        print("Token: \(UserDefaultHelper.shared.accessToken ?? "No token") 123")
    }
    
    func setupUI(){
        lbUser.text = "Hi, " + (UserDefaultHelper.shared.userName ?? "Username")
        lbSpeaker.transform = CGAffineTransform(rotationAngle: CGFloat.pi / 2)
        timer = Timer.scheduledTimer(timeInterval: 3, target: self, selector: #selector(fetchData), userInfo: nil, repeats: true)
    }
    
    @objc func randomNum(){
        lbTemp.text = String(Int.random(in: 0...100)) + "°C"
        lbHumid.text = String(Int.random(in: 0...100)) + "%"
    }
    
    @objc func fetchData(){
        if isCallTimer {
            presenter.getTemperature()
            presenter.getHumidity()
        }
    }
    
    @IBAction func onTapPofile(_ sender: Any) {
        navigationController?.pushViewController(ProfileViewController(presenter: ProfilePresenter()), animated: true)
    }
    
    @IBAction func onTapGraph(_ sender: Any) {
        
    }
    
    @IBAction func onTapSpeaker(_ sender: Any) {
        
    }
    
    @IBAction func onTapSettings(_ sender: Any) {
        navigationController?.pushViewController(SettingsViewController(presenter: SettingsPresenter()), animated: true)
    }
    
    @IBAction func onTapHistory(_ sender: Any) {
        
    }
}

extension HomeViewController: HomeViewProtocol{
    func getHumidSuccess() {
        HUD.hide()
        lbHumid.text = (presenter.humid?.value ?? "") + "%"
    }
    
    func getHumidFailed(error: String) {
        HUD.hide()
        lbHumid.text = "..."
        showAlert("Error", message: error)
    }
    
    func getTempSuccess() {
        HUD.hide()
        lbTemp.text = (presenter.temperature?.value ?? "") + "°C"
    }
    
    func getTempFailed(error: String) {
        HUD.hide()
        lbTemp.text = "..."
        showAlert("Error", message: error)
    }
    
    
}
