//
//  HomePresenter.swift
//  Hu&Te
//
//  Created BigSur on 20/05/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol HomeViewProtocol: class {

}

// MARK: Presenter -
protocol HomePresenterProtocol: class {
	var view: HomeViewProtocol? { get set }
    func viewDidLoad()
}

class HomePresenter: HomePresenterProtocol {

    weak var view: HomeViewProtocol?

    func viewDidLoad() {

    }
}
