# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hu&Te' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hu&Te
  pod 'MaterialComponents/BottomSheet'
  pod 'ObjectMapper', '3.5.2'
  pod 'SDWebImage', '5.6.1'
  pod 'SwiftyJSON'
  pod "PKHUD"
  pod 'Alamofire', '4.9.1'
  pod 'Charts'

end
