//
//  GraphViewController.swift
//  Hu&Te
//
//  Created BigSur on 21/05/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class GraphViewController: UIViewController, GraphViewProtocol {

    @IBOutlet weak var vNavigation: NavigationView!
    var presenter: GraphPresenterProtocol

	init(presenter: GraphPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "GraphViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()
        presenter.view = self
        setupUI()
    }
    
    func setupUI(){
        vNavigation.setupNavigation(title: "Graph", rightTitle: nil)
    }

}
