//
//  GraphPresenter.swift
//  Hu&Te
//
//  Created BigSur on 21/05/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol GraphViewProtocol: class {

}

// MARK: Presenter -
protocol GraphPresenterProtocol: class {
	var view: GraphViewProtocol? { get set }
    func viewDidLoad()
}

class GraphPresenter: GraphPresenterProtocol {

    weak var view: GraphViewProtocol?

    func viewDidLoad() {

    }
}
