//
//  SettingsPresenter.swift
//  Hu&Te
//
//  Created BigSur on 21/05/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol SettingsViewProtocol: class {

}

// MARK: Presenter -
protocol SettingsPresenterProtocol: class {
	var view: SettingsViewProtocol? { get set }
    func viewDidLoad()
}

class SettingsPresenter: SettingsPresenterProtocol {

    weak var view: SettingsViewProtocol?

    func viewDidLoad() {

    }
}
