//
//  SettingsViewController.swift
//  Hu&Te
//
//  Created BigSur on 21/05/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class SettingsViewController: UIViewController, SettingsViewProtocol {

    @IBOutlet weak var vNavigation: NavigationView!
    @IBOutlet weak var imgSpeakerStatus: UIImageView!
    var presenter: SettingsPresenterProtocol
    var speakerStatus: Bool = true {
        didSet {
            if speakerStatus {
                imgSpeakerStatus.image = #imageLiteral(resourceName: "ic_speaker_on")
            } else {
                imgSpeakerStatus.image = #imageLiteral(resourceName: "ic_speaker_off")
            }
        }
    }

	init(presenter: SettingsPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "SettingsViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()
        presenter.view = self
        setupUI()
    }
    
    func setupUI(){
        vNavigation.setupNavigation(title: "Settings", rightTitle: "Save")
        vNavigation.onTapBack = {
            self.navigationController?.popViewController(animated: true)
        }
    }

    @IBAction func onTapSwitchButton(_ sender: Any) {
        speakerStatus = !speakerStatus
    }
}
