//
//  GraphDetailPresenter.swift
//  Hu&Te
//
//  Created BigSur on 04/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol GraphDetailViewProtocol: class {

}

// MARK: Presenter -
protocol GraphDetailPresenterProtocol: class {
	var view: GraphDetailViewProtocol? { get set }
    func viewDidLoad()
}

class GraphDetailPresenter: GraphDetailPresenterProtocol {

    weak var view: GraphDetailViewProtocol?

    func viewDidLoad() {

    }
}
