//
//  GraphDetailViewController.swift
//  Hu&Te
//
//  Created BigSur on 04/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class GraphDetailViewController: UIViewController, GraphDetailViewProtocol {

	var presenter: GraphDetailPresenterProtocol

	init(presenter: GraphDetailPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "GraphDetailViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()

        presenter.view = self
        presenter.viewDidLoad()
    }

}
