//
//  ProfilePresenter.swift
//  Hu&Te
//
//  Created BigSur on 20/05/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol ProfileViewProtocol: class {

}

// MARK: Presenter -
protocol ProfilePresenterProtocol: class {
	var view: ProfileViewProtocol? { get set }
    func viewDidLoad()
}

class ProfilePresenter: ProfilePresenterProtocol {

    weak var view: ProfileViewProtocol?

    func viewDidLoad() {

    }
}
