//
//  ProfileViewController.swift
//  Hu&Te
//
//  Created BigSur on 20/05/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit
import MaterialComponents.MaterialBottomSheet

class ProfileViewController: UIViewController, ProfileViewProtocol {

    @IBOutlet weak var vNavigation: NavigationView!
    @IBOutlet weak var tfName: UITextField!
    @IBOutlet weak var tfEmail: UITextField!
    @IBOutlet weak var tfPhone: UITextField!
    var presenter: ProfilePresenterProtocol

	init(presenter: ProfilePresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "ProfileViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()
        presenter.view = self
        setupUI()
    }
    
    func setupUI(){
        vNavigation.setupNavigation(title: "Profile", rightTitle: "Manage")
        vNavigation.onTapRightButton = {
            
        }
        vNavigation.onTapBack = {
            self.navigationController?.popViewController(animated: true)
        }
    }

    @IBAction func onTapChangePassword(_ sender: Any) {
        let bottomSheet = MDCBottomSheetController(contentViewController: ChangePasswordViewController(presenter: ChangePasswordPresenter()))
        bottomSheet.preferredContentSize = CGSize(width: UIScreen.screenWidth(), height: UIScreen.screenHeight())
        self.present(bottomSheet, animated: true, completion: nil)
    }
    
    @IBAction func onTapLogout(_ sender: Any) {
        let alert = UIAlertController(title: "Logout", message: "Would you like to logout the application?", preferredStyle: UIAlertController.Style.alert)
        alert.addAction(UIAlertAction(title: "Logout", style: UIAlertAction.Style.destructive, handler: {_ in
            UserDefaultHelper.shared.accessToken = nil
            UserDefaultHelper.shared.userId = nil
            UserDefaultHelper.shared.userName = nil
            UserDefaultHelper.shared.isAdmin = nil
            AppRouter.shared.updateRootView()
        }))
        alert.addAction(UIAlertAction(title: "Cancel", style: UIAlertAction.Style.cancel, handler: nil))
        self.present(alert, animated: true, completion: nil)
        
    }
}
