//
//  ChangePasswordViewController.swift
//  Hu&Te
//
//  Created BigSur on 20/05/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit

class ChangePasswordViewController: UIViewController, ChangePasswordViewProtocol {

    var presenter: ChangePasswordPresenterProtocol
    @IBOutlet weak var tfCurentPassword: InputView!
    @IBOutlet weak var tfNewPassword: InputView!
    @IBOutlet weak var tfConfirmPassword: InputView!
    
    init(presenter: ChangePasswordPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "ChangePasswordViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()
        presenter.view = self
        setupUI()
    }
    
    func setupUI(){
        tfCurentPassword.setupData(title: "Current Password")
        tfNewPassword.setupData(title: "New Password")
        tfConfirmPassword.setupData(title: "Confirm Password")
    }
    
    @IBAction func onTapDismiss(_ sender: Any) {
        self.dismiss(animated: true, completion: nil)
    }
    
    @IBAction func onTapSubmit(_ sender: Any) {
    }
}
