//
//  ChangePasswordPresenter.swift
//  Hu&Te
//
//  Created BigSur on 20/05/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol ChangePasswordViewProtocol: class {

}

// MARK: Presenter -
protocol ChangePasswordPresenterProtocol: class {
	var view: ChangePasswordViewProtocol? { get set }
    func viewDidLoad()
}

class ChangePasswordPresenter: ChangePasswordPresenterProtocol {

    weak var view: ChangePasswordViewProtocol?

    func viewDidLoad() {

    }
}
