//
//  HistoryViewController.swift
//  Hu&Te
//
//  Created BigSur on 08/06/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Edward
//

import UIKit
import Charts
import PKHUD

class HistoryViewController: UIViewController, HistoryViewProtocol {
    @IBOutlet weak var lbDate: UILabel!
    @IBOutlet weak var imgType: UIImageView!
    @IBOutlet weak var vNavigation: NavigationView!
    @IBOutlet weak var datePicker: UIDatePicker!
    @IBOutlet weak var vChart: LineChartView!
    @IBOutlet weak var vDatePicker: UIView!
    var presenter: HistoryPresenterProtocol
    var isTemperature: Bool = true {
        didSet {
            vChart.clear()
            vChart.clearValues()
            //vChart.clearAllViewportJobs()
            if isTemperature {
                imgType.image = #imageLiteral(resourceName: "Group 32")
                presenter.type = .Temperature
                vChart.leftAxis.valueFormatter = temperatureAxisFormatter()
                
            } else {
                imgType.image = #imageLiteral(resourceName: "Group 33")
                presenter.type = .Humidity
                vChart.leftAxis.valueFormatter = humidAxisFormatter()
            }
            presenter.setupChartData()
        }
    }

	init(presenter: HistoryPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "HistoryViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

	override func viewDidLoad() {
        super.viewDidLoad()
        presenter.view = self
        presenter.fetchData(dateInput: Date())
        setupUI()
    }

    func setupUI(){
        lbDate.text = getDate(date: Date())
        vNavigation.lbTitle.text = "History"
        vNavigation.onTapBack = {
            self.navigationController?.popViewController(animated: true)
        }
        vNavigation.lbRightTitle.text = "Change date"
        vNavigation.onTapRightButton = {
            self.vDatePicker.isHidden = false
        }
        vChart.rightAxis.enabled = false
        vChart.xAxis.labelPosition = .bottom
        vChart.leftAxis.granularity = 1
        vChart.xAxis.granularity = 60
        vChart.xAxis.valueFormatter = timeAxisFormatter()
        vChart.leftAxis.valueFormatter = temperatureAxisFormatter()
        vChart.xAxis.labelCount = 10
        vChart.leftAxis.labelCount = 10
        vChart.delegate = self
    }
    
    @IBAction func onTapChangeType(_ sender: Any) {
        isTemperature = !isTemperature
    }
    @IBAction func onTapDone(_ sender: Any) {
        vDatePicker.isHidden = true
        lbDate.text = getDate(date: datePicker.date)
        presenter.fetchData(dateInput: datePicker.date)
    }
}

extension HistoryViewController: ChartViewDelegate {
    func chartValueSelected(_ chartView: ChartViewBase, entry: ChartDataEntry, highlight: Highlight) {
//        print(entry)
//        let (h,m,_) = secondsToHoursMinutesSeconds(seconds: Int(entry.x))
//        lbTimeDetail.text = "At " + (h <= 9 ? "0" +  String(h) : String(h)) + ":" + (m <= 9 ? "0" +  String(m) : String(m))
//        lbValueDetail.text = String(Int(entry.y)) + (presenter.type == .Temperature ? "°C" : "%")
//        vDetail.isHidden = false
//        vDetail.alpha = 1
//        UIView.animate(withDuration: 1, delay: 2, options: UIView.AnimationOptions.transitionFlipFromTop, animations: {
//            self.vDetail.alpha = 0
//        }, completion: nil)
    }
    
    func getDataSuccess() {
        lbDate.text = getDate(date: Date())
        let set = LineChartDataSet(entries: presenter.chartData, label: presenter.type == .Temperature ? "Temperature" : "Humidity")
        set.drawCirclesEnabled = false
        
        set.setColor(presenter.type == .Temperature ? #colorLiteral(red: 0.9372549057, green: 0.3490196168, blue: 0.1921568662, alpha: 1) : #colorLiteral(red: 0.2588235438, green: 0.7568627596, blue: 0.9686274529, alpha: 1))
        set.lineWidth = 3
        set.fill = Fill(color: presenter.type == .Temperature ? #colorLiteral(red: 0.9372549057, green: 0.3490196168, blue: 0.1921568662, alpha: 1) : #colorLiteral(red: 0.2588235438, green: 0.7568627596, blue: 0.9686274529, alpha: 1))
        set.fillAlpha = 0.8
        set.drawFilledEnabled = true
        set.highlightColor = presenter.type == .Temperature ? #colorLiteral(red: 0.9372549057, green: 0.3490196168, blue: 0.1921568662, alpha: 1) : #colorLiteral(red: 0.2588235438, green: 0.7568627596, blue: 0.9686274529, alpha: 1)
        set.highlightLineWidth = 1.5
        let data = LineChartData(dataSet: set)
        self.vChart.data = data
        data.notifyDataChanged()
        vChart.notifyDataSetChanged()
        vChart.isHidden = false
        vChart.animate(xAxisDuration: 5)
        vChart.setNeedsDisplay()
    }
    
    func getDataFailed(error: String) {
        showAlert("Error", message: "Something went wrong!")
    }
    
    func secondsToHoursMinutesSeconds (seconds : Int) -> (Int, Int, Int) {
      return (seconds / 3600, (seconds % 3600) / 60, (seconds % 3600) % 60)
    }
    
    func getDate(date: Date) -> String{
        //let date = Date()
        let iso8601DateFormatter = ISO8601DateFormatter()
        iso8601DateFormatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        let now = iso8601DateFormatter.string(from: date)
        return String(now.prefix(10))
    }
}
